name: Promote to stage

on:
  push:
    branches: [ dev, master, breaking ]

jobs:
  build-images:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: setup-env
      run: |
        echo "::set-env name=ZKSYNC_HOME::$(pwd)"
        echo "::set-env name=PATH::$(echo `pwd`/bin:$PATH)"
        echo "::set-env name=CI::1"

    - name: init
      run: |
        zksync yarn
        cp etc/tokens/{test,localhost}.json
        zksync verify-keys unpack

    - name: update-images
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        zksync update-images
        echo "::set-env name=IMAGE_TAG::$(f sh -c 'echo $IMAGE_TAG')"

    - name: promote-to-gitlab
      run: |
        curl -X POST \
         -F token=${{ secrets.GITLAB_TOKEN }} \
         -F "ref=gitlab-deploy" \
         -F "variables[SERVER_TAG]=$IMAGE_TAG" \
         -F "variables[PROVER_TAG]=$IMAGE_TAG" \
         -F "variables[EXPLORER_TAG]=$IMAGE_TAG" \
         -F "variables[GITHUB_REF]=$GITHUB_REF" \
         https://gitlab.com/api/v4/projects/19165314/trigger/pipeline
